name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.amazon_ssh }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.214.129 >> ~/.ssh/known_hosts

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@13.60.214.129 << 'EOF'
          cd /home/ec2-user/Nursery-System-Website
          
          # Pull the latest code from Git
          git pull
          
          # Add environment variables to .env file using GitHub Secrets
          echo "SECRETKEY='MySecretCODE555d432s5'" > .env
          echo "URL_DATABASE='${{ secrets.database_url }}'" >> .env
          echo "PORT=${{ secrets.port }}" >> .env
          
          # Install dependencies
          npm install
          
          # Restart the application with PM2
          node app
