name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.amazon_ssh }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.61.185.81 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -T -i ~/.ssh/id_rsa ec2-user@13.60.214.129 "echo Connected successfully"

      - name: Deploy to EC2
        run: |
          ssh -T -i ~/.ssh/id_rsa ec2-user@13.61.185.81 << 'EOF'
          cd /home/ec2-user/Nursery-System-Website
          git pull
          echo "SECRETKEY='MySecretCODE555d432s5'" > .env
          echo "URL_DATABASE='${{ secrets.DATABASE_URL }}'" >> .env
          echo "PORT=8080" >> .env
          npm install
          pm2 start app.js --name app || pm2 restart app --update-env
          EOF
